import type { Locale } from './locales';

export const APARTMENT_DESCRIPTIONS: Record<'magma-104' | 'magma-102', Record<Locale, string>> = {
  'magma-104': {
    it: "Dimora di charme in pietra lavica nel cuore di Pedara, alle pendici dell'Etna. Un appartamento accogliente e curato, dove il fascino dell'architettura siciliana incontra il comfort moderno. Ambienti luminosi, spazi funzionali e una caratteristica corte esterna attrezzata — la posizione ideale per scoprire l'Etna, i borghi vicini e la Sicilia orientale.",
    es: 'Alojamiento con encanto en piedra volcánica en el corazón de Pedara, en las laderas del Etna. Un apartamento acogedor y cuidado, donde el encanto de la arquitectura siciliana se une al confort moderno. Espacios luminosos y funcionales, y un característico patio exterior equipado — la ubicación ideal para descubrir el Etna, los pueblos cercanos y la Sicilia oriental.',
    en: "Charming lava-stone residence in the heart of Pedara, on the slopes of Mount Etna. A cosy, well-kept apartment where Sicilian architecture meets modern comfort. Bright, functional rooms and a distinctive furnished outdoor courtyard — the ideal base for exploring Etna, nearby villages and eastern Sicily.",
    fr: "Demeure de charme en pierre de lave au cœur de Pedara, sur les flancs de l'Etna. Un appartement chaleureux et soigné, où le charme de l'architecture sicilienne rencontre le confort moderne. Espaces lumineux et fonctionnels, et une cour extérieure aménagée caractéristique — l'emplacement idéal pour découvrir l'Etna, les villages voisins et la Sicile orientale.",
    de: 'Charmantes Anwesen aus Lavastein im Herzen von Pedara, an den Hängen des Ätna. Ein gemütliches, gepflegtes Apartment, in dem sizilianische Architektur auf modernen Komfort trifft. Helle, funktionale Räume und ein charakteristischer, möblierter Außenhof — die ideale Lage, um den Ätna, die umliegenden Dörfer und den Osten Siziliens zu entdecken.',
  },
  'magma-102': {
    it: "Dimora di charme in pietra lavica nel cuore di Pedara, alle pendici dell'Etna. Un monolocale accogliente e curato, dove il fascino dell'architettura siciliana incontra il comfort moderno. Zona notte e zona soggiorno in un unico ambiente luminoso, con una caratteristica corte esterna attrezzata — la posizione ideale per scoprire l'Etna, i borghi vicini e la Sicilia orientale.",
    es: 'Alojamiento con encanto en piedra volcánica en el corazón de Pedara, en las laderas del Etna. Un estudio acogedor y cuidado, donde el encanto de la arquitectura siciliana se une al confort moderno. Zona de noche y de estar en un único ambiente luminoso, con un característico patio exterior equipado — la ubicación ideal para descubrir el Etna, los pueblos cercanos y la Sicilia oriental.',
    en: "Charming lava-stone residence in the heart of Pedara, on the slopes of Mount Etna. A cosy, well-kept studio where Sicilian architecture meets modern comfort. Sleeping and living area in one bright room, with a distinctive furnished outdoor courtyard — the ideal base for exploring Etna, nearby villages and eastern Sicily.",
    fr: "Demeure de charme en pierre de lave au cœur de Pedara, sur les flancs de l'Etna. Un studio chaleureux et soigné, où le charme de l'architecture sicilienne rencontre le confort moderne. Coin nuit et coin séjour dans un même espace lumineux, avec une cour extérieure aménagée caractéristique — l'emplacement idéal pour découvrir l'Etna, les villages voisins et la Sicile orientale.",
    de: 'Charmantes Anwesen aus Lavastein im Herzen von Pedara, an den Hängen des Ätna. Ein gemütliches, gepflegtes Studio, in dem sizilianische Architektur auf modernen Komfort trifft. Schlaf- und Wohnbereich in einem hellen Raum, mit einem charakteristischen, möblierten Außenhof — die ideale Lage, um den Ätna, die umliegenden Dörfer und den Osten Siziliens zu entdecken.',
  },
};
