import type { Locale } from './locales';

export const APARTMENT_DESCRIPTIONS: Record<'magma-104' | 'magma-102', Record<Locale, string>> = {
  'magma-104': {
    it: "Immagina di svegliarti nel cuore di Pedara, tra le pareti di pietra lavica di una dimora che racconta secoli di storia siciliana — e di uscire in corte, un caffè in mano, con l'Etna che fuma silenzioso all'orizzonte. Magma 104 è pensato per chi cerca un rifugio elegante e riservato: camera da letto separata, ambienti curati nei minimi dettagli e tutti i comfort per sentirsi a casa fin dal primo istante. Perfetto per una coppia in cerca di romanticismo, o per una famiglia con un bimbo piccolo (box bebè incluso). La corte esterna attrezzata, condivisa solo con gli ospiti di Magma 102, è il posto ideale per un aperitivo al tramonto prima di partire alla scoperta dei sentieri dell'Etna, a due passi da qui.",
    es: 'Imagina despertarte en el corazón de Pedara, entre los muros de piedra volcánica de una casa que cuenta siglos de historia siciliana — y salir al patio, café en mano, con el Etna humeando silencioso en el horizonte. Magma 104 está pensado para quienes buscan un refugio elegante y reservado: dormitorio separado, espacios cuidados hasta el último detalle y todas las comodidades para sentirse como en casa desde el primer momento. Perfecto para una pareja en busca de romanticismo, o para una familia con un bebé pequeño (cuna de viaje incluida). El patio exterior equipado, compartido solo con los huéspedes de Magma 102, es el lugar ideal para un aperitivo al atardecer antes de salir a descubrir los senderos del Etna, a un paso de aquí.',
    en: "Picture waking up in the heart of Pedara, within the lava-stone walls of a home that carries centuries of Sicilian history — then stepping out into the courtyard, coffee in hand, with Etna smouldering quietly on the horizon. Magma 104 is built for those seeking an elegant, private retreat: a separate bedroom, spaces finished down to the last detail, and every comfort to feel at home from the moment you arrive. Perfect for a couple after some romance, or a family with a young child (travel crib included). The furnished outdoor courtyard, shared only with Magma 102's guests, is the ideal spot for a sunset drink before setting off to explore Etna's trails, just minutes away.",
    fr: "Imaginez-vous vous réveiller au cœur de Pedara, entre les murs en pierre de lave d'une demeure qui raconte des siècles d'histoire sicilienne — puis sortir dans la cour, café à la main, avec l'Etna qui fume silencieusement à l'horizon. Magma 104 est pensé pour qui cherche un refuge élégant et intime : chambre séparée, espaces soignés jusque dans les moindres détails, et tout le confort pour se sentir chez soi dès l'arrivée. Parfait pour un couple en quête de romantisme, ou pour une famille avec un jeune enfant (lit parapluie inclus). La cour extérieure aménagée, partagée uniquement avec les hôtes de Magma 102, est l'endroit idéal pour un apéritif au coucher du soleil avant de partir explorer les sentiers de l'Etna, à deux pas d'ici.",
    de: 'Stellen Sie sich vor, im Herzen von Pedara aufzuwachen, zwischen den Lavastein-Mauern eines Hauses, das Jahrhunderte sizilianischer Geschichte erzählt — und dann mit einem Kaffee in der Hand in den Innenhof zu treten, während der Ätna still am Horizont raucht. Magma 104 ist für alle gemacht, die ein elegantes, privates Rückzugsort suchen: separates Schlafzimmer, bis ins letzte Detail gepflegte Räume und jeder Komfort, um sich vom ersten Moment an zu Hause zu fühlen. Perfekt für ein Paar auf der Suche nach Romantik oder eine Familie mit kleinem Kind (Reisebett inklusive). Der möblierte Außenhof, der nur mit den Gästen von Magma 102 geteilt wird, ist der ideale Ort für einen Sundowner, bevor es hinaus auf die Wanderwege des Ätna geht, nur wenige Minuten entfernt.',
  },
  'magma-102': {
    it: "Un monolocale luminoso e vissuto, pensato per chi vuole il massimo della libertà: zona notte e soggiorno si fondono in un unico ambiente in pietra lavica, arredato con gusto essenziale e tutto il necessario per sentirsi autonomi fin dal check-in. Magma 102 ospita fino a 3 persone — ideale per un gruppo di amici in viaggio, o per chi cerca uno spazio comodo e flessibile senza rinunciare al carattere di una vera casa siciliana. La corte esterna attrezzata è il punto d'incontro perfetto per raccontarsi la giornata dopo un'escursione sull'Etna, tra un bicchiere di vino locale e il profumo della macchia mediterranea.",
    es: 'Un estudio luminoso y con carácter, pensado para quienes quieren máxima libertad: la zona de noche y el salón se funden en un único ambiente en piedra volcánica, decorado con gusto esencial y todo lo necesario para sentirse autónomos desde el check-in. Magma 102 acoge hasta 3 personas — ideal para un grupo de amigos de viaje, o para quienes buscan un espacio cómodo y flexible sin renunciar al carácter de una auténtica casa siciliana. El patio exterior equipado es el punto de encuentro perfecto para contarse el día después de una excursión al Etna, entre una copa de vino local y el aroma de la vegetación mediterránea.',
    en: "A bright, characterful studio built for maximum freedom: the sleeping and living areas flow into one lava-stone room, furnished with understated style and everything you need to feel independent from check-in. Magma 102 sleeps up to 3 — perfect for a group of friends on the road, or anyone after a comfortable, flexible space without giving up the character of a real Sicilian home. The furnished outdoor courtyard is the perfect spot to swap stories after a day exploring Etna, over a glass of local wine and the scent of Mediterranean scrubland.",
    fr: "Un studio lumineux et plein de caractère, pensé pour qui veut un maximum de liberté : le coin nuit et le séjour se fondent en un seul espace en pierre de lave, meublé avec un style sobre et tout le nécessaire pour se sentir autonome dès l'arrivée. Magma 102 accueille jusqu'à 3 personnes — idéal pour un groupe d'amis en voyage, ou pour qui cherche un espace confortable et flexible sans renoncer au caractère d'une authentique maison sicilienne. La cour extérieure aménagée est le lieu de rencontre parfait pour se raconter la journée après une excursion sur l'Etna, autour d'un verre de vin local et du parfum du maquis méditerranéen.",
    de: 'Ein helles, charaktervolles Studio, gemacht für maximale Freiheit: Schlaf- und Wohnbereich verschmelzen in einem einzigen Raum aus Lavastein, mit schlichtem Stil eingerichtet und allem, was man braucht, um sich vom Check-in an unabhängig zu fühlen. Magma 102 bietet Platz für bis zu 3 Personen — ideal für eine Gruppe von Freunden auf Reisen oder für alle, die einen komfortablen, flexiblen Raum suchen, ohne auf den Charakter eines echten sizilianischen Hauses zu verzichten. Der möblierte Außenhof ist der perfekte Treffpunkt, um sich nach einem Tag auf dem Ätna bei einem Glas lokalem Wein und dem Duft der mediterranen Macchia den Tag zu erzählen.',
  },
};
